### ISSUE TITLE
"Exception: Bad spec #"

### ISSUE THREAD

**Issue by mokagio** [schwa/punic#12]
Adding [this repo](https://gitlab.com/mokagio/punic-cartfile-issue) as dependency results in this error:

```
Build
Using xcode version: /Applications/Xcode.app (8.0)
Fetching: xmkevinchen/JSONCodable
Fetching: antitypical/Result
Fetching: ReactiveCocoa/ReactiveSwift
Fetching: ReactiveCocoa/ReactiveCocoa
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic==0.1.19', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 356, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 146, in build
    punic.build(dependencies=deps)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 84, in build
    filtered_dependencies = self._ordered_dependencies(name_filter=dependencies)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 134, in _ordered_dependencies
    resolved_dependencies = self._resolver().resolve_versions(dependencies)
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 129, in resolve_versions
    dependencies_for_node = self._dependencies_for_node(Node(identifier, version))
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 141, in _dependencies_for_node
    return self.dependencies_for_node(node)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 42, in _dependencies_for_node
    dependencies = self.dependencies_for_project_and_tag(identifier=node.identifier, tag=node.version)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 156, in dependencies_for_project_and_tag
    specifications = repository.specifications_for_revision(tag)
  File "/usr/local/lib/python2.7/site-packages/punic/repository.py", line 150, in specifications_for_revision
    cartfile.read(data)
  File "/usr/local/lib/python2.7/site-packages/punic/cartfile.py", line 30, in read
    self.specifications = [Specification.cartfile_string(line, use_ssh=self.use_ssh, overrides=self.overrides) for line in lines]
  File "/usr/local/lib/python2.7/site-packages/punic/specification.py", line 52, in cartfile_string
    raise Exception('Bad spec {}'.format(string))
Exception: Bad spec #
```

I've updated my [example repo](https://github.com/mokagio/carthage-punic-diff) for easier reproducibly ;)

**Comment by schwa** [comment]
Hmmm so cannot reproduce with unit tests. This behaves as expected:

```from punic.specification import *

spec = Specification.cartfile_string('git "git@gitlab.com:mokagio/punic-cartfile-issue.git" "master"')

print(spec.identifier.__dict__)```

```{'source': 'git', 'team_name': None, 'project_name': 'punic-cartfile-issue', 'remote_url': 'git@gitlab.com:mokagio/punic-cartfile-issue.git'}
```

I'll try your repo now.

**Comment by schwa** [comment]
And when running `punic resolve` inside your sample repo I get a different error.

Are you sure you got the URLs correct?

Looks like it parsed the spec file correctly but couldn't clone the gitlab repo.

```
The authenticity of host 'gitlab.com (104.210.2.228)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? yes
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic', 'console_scripts', 'punic')()
  File "/Users/schwa/Projects/python-punic/punic/punic_cli.py", line 356, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/schwa/Projects/python-punic/punic/punic_cli.py", line 119, in resolve
    punic.resolve()
  File "/Users/schwa/Projects/python-punic/punic/__init__.py", line 48, in resolve
    build_order = resolver.resolve_build_order()
  File "/Users/schwa/Projects/python-punic/punic/resolver.py", line 112, in resolve_build_order
    graph = self.resolve()
  File "/Users/schwa/Projects/python-punic/punic/resolver.py", line 40, in resolve
    for dependency, revisions in self._dependencies_for_node(self.root):
  File "/Users/schwa/Projects/python-punic/punic/resolver.py", line 141, in _dependencies_for_node
    return self.dependencies_for_node(node)
  File "/Users/schwa/Projects/python-punic/punic/__init__.py", line 42, in _dependencies_for_node
    dependencies = self.dependencies_for_project_and_tag(identifier=node.identifier, tag=node.version)
  File "/Users/schwa/Projects/python-punic/punic/__init__.py", line 167, in dependencies_for_project_and_tag
    return [make(specification) for specification in specifications]
  File "/Users/schwa/Projects/python-punic/punic/__init__.py", line 159, in make
    repository = self._repository_for_identifier(specification.identifier)
  File "/Users/schwa/Projects/python-punic/punic/__init__.py", line 145, in _repository_for_identifier
    repository.fetch()
  File "/Users/schwa/Projects/python-punic/punic/repository.py", line 107, in fetch
    runner.check_run('git clone --recursive "{}" "{}"'.format(repo, str(self.path)), cwd=self.path.parent)
  File "/Users/schwa/Projects/python-punic/punic/runner.py", line 70, in check_run
    result = self.run(*args, **kwargs)
  File "/Users/schwa/Projects/python-punic/punic/runner.py", line 123, in run
    raise CalledProcessError(return_code, command, stdout)
subprocess.CalledProcessError: Command 'git clone --recursive "git@gitlab.com:mokagio/punic-cartfile-issue.git" "/Users/schwa/Library/Application Support/io.schwa.Punic/repo_cache/punic-cartfile-issue_466ebe24b11e2f6f9dbd26b05adb3c90"' returned non-zero exit status 128
```

**Comment by schwa** [comment]
Alright. No response - so closing this. If still an issue please re-open.
