### ISSUE TITLE
Exception: "1.6.5.1" not a semantic version

### ISSUE THREAD

**Issue by aducret** [schwa/punic#14]
Hi @schwa! Thanks for your work! :)

I just create a `Cartfile`:
```
github "CocoaLumberjack/CocoaLumberjack" ~> 2.4.0
```

When I run `punic resolve` I get: 
```
Resolve
Fetching: CocoaLumberjack/CocoaLumberjack
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic==0.1.20', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 356, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 119, in resolve
    punic.resolve()
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 48, in resolve
    build_order = resolver.resolve_build_order()
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 112, in resolve_build_order
    graph = self.resolve()
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 40, in resolve
    for dependency, revisions in self._dependencies_for_node(self.root):
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 141, in _dependencies_for_node
    return self.dependencies_for_node(node)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 42, in _dependencies_for_node
    dependencies = self.dependencies_for_project_and_tag(identifier=node.identifier, tag=node.version)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 167, in dependencies_for_project_and_tag
    return [make(specification) for specification in specifications]
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 160, in make
    tags = repository.revisions_for_predicate(specification.predicate)
  File "/usr/local/lib/python2.7/site-packages/punic/repository.py", line 158, in revisions_for_predicate
    return [tag for tag in self.tags if predicate.test(tag.semantic_version)]
  File "/usr/local/lib/python2.7/site-packages/memoize.py", line 11, in _property
    setattr(self, attribute, fn(self))
  File "/usr/local/lib/python2.7/site-packages/punic/repository.py", line 68, in tags
    tags = [Revision(repository=self, revision=tag, revision_type=Revision.Type.tag) for tag in tags if SemanticVersion.is_semantic(tag)]
  File "/usr/local/lib/python2.7/site-packages/punic/repository.py", line 180, in __init__
    self.semantic_version = (SemanticVersion.string(self.revision) if self.revision_type == Revision.Type.tag else None)
  File "/usr/local/lib/python2.7/site-packages/punic/semantic_version.py", line 125, in string
    raise Exception('"{}" not a semantic version.'.format(s))
Exception: "1.6.5.1" not a semantic version.
```

**Comment by schwa** [comment]
So 1.6.5.1 according to semver.org is _not_ a valid semantic version number. I can perhaps try and make my code more forgiving of bad versions but essentially that version of Cocoa lumberjack isn't valid. I'll see what I can do though.

**Comment by aducret** [comment]
yes I don't know why Cocoa Lumberjack use an invalid semantic version, but as you said maybe it's better to be more forgiving in this cases.

Thanks for your answer! 😄

**Comment by schwa** [comment]
Alright - I was already filtering out tags that weren't semantic - but this type of tag was falling through the filter.

I've fixed the semantic version parsing so it is consistent - and also logged non-semantic tags if the `--verbose` switch is used.

This will be on develop (`pip install -U git+https://github.com/schwa/punic@develop`) very shortly and in next version release later.

```
Resolve
Fetching: CocoaLumberjack/CocoaLumberjack
Warning: Found tags in 'CocoaLumberjack/CocoaLumberjack' that are not semantic: '1.6.5.1'
CocoaLumberjack/CocoaLumberjack [2.4.0, 3.0.0]
Building universal graph
Universal graph has 3 nodes, 2 edges.
Pruning graph
Pruned universal graph has 2 nodes, 1 edges.
Pruned universal graph has 2 nodes, 1 edges.
Topologically sorting graph
1 CocoaLumberjack/CocoaLumberjack 3.0.0 https://github.com/CocoaLumberjack/CocoaLumberjack.git
Saving Cartfile.resolved
```
