### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by siuying** [schwa/punic#16]
Build error:

```
$ punic version
Punic version: 0.1.21
Python version: 2.7.12
 $ punic update
Update
Fetching: CocoaLumberjack/CocoaLumberjack
Using xcode version: /Applications/Xcode.app (8.0)
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic==0.1.21', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 356, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 170, in update
    punic.build(dependencies=deps)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 115, in build
    if not filter_dependency(platform, checkout, project, scheme):
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 97, in filter_dependency
    for skip in skips:
TypeError: 'NoneType' object is not iterable
```

**Comment by schwa** [comment]
Can I get your Cartfile and/or punic.yaml file?

Thanks.

**Comment by siuying** [comment]
Thanks!

### punic.yaml
```
defaults:
  configuration: Release
  platform: iOS
  xcode-version: '8.0'
skips:
```

### Cartfile
```
github "CocoaLumberjack/CocoaLumberjack" "3.0.0"
```

**Comment by schwa** [comment]
Oddly enough I cannot reproduce this.

Are you definitely on the latest version? 0.1.21?

`pip install -U punic` will update you.

**Comment by schwa** [comment]
If put in a possible fix - before updating to latest punic can you try again locally?

Thanks.

**Comment by siuying** [comment]
I install via git and confirm the issue is fixed. Thanks a lot for figure it out!
