### ISSUE TITLE
Punic should skip repositories without projects or framework targets.

### ISSUE THREAD

**Issue by calebd** [schwa/punic#17]
# To help reproduce issues with punic please attach your project's Cartfile, Cartfile.resolved and punic.yaml if possible.

A `Cartfile.private` like this:

```
github "jspahrsummers/xcconfigs"
``` 

fails with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 369, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 147, in build
    punic.build(dependencies=deps)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 109, in build
    for project in checkout.projects:
  File "/usr/local/lib/python2.7/site-packages/punic/checkout.py", line 98, in projects
    raise Exception("No projects found in {}".format(self.checkout_path))
Exception: No projects found in $PWD/Carthage/Checkouts/xcconfigs
```

**Comment by schwa** [comment]
Good catch - will be in next release
