### ISSUE TITLE
punic search Async failed

### ISSUE THREAD

**Issue by lexrus** [schwa/punic#18]
``` bash
punic search Async
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 11, in <module>
    load_entry_point('punic==0.2.1', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 369, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 365, in search
    github_search(punic, name, cartfile_append=append, language=language)
  File "/usr/local/lib/python2.7/site-packages/punic/search.py", line 29, in github_search
    repositories = GitHub().search(name, language = language)
  File "/usr/local/lib/python2.7/site-packages/punic/github.py", line 43, in search
    r = requests.get('https://api.github.com/search/repositories?q={}&sort=stars'.format(q), auth = self.auth, headers = headers)
  File "/usr/local/lib/python2.7/site-packages/memoize.py", line 11, in _property
    setattr(self, attribute, fn(self))
  File "/usr/local/lib/python2.7/site-packages/punic/github.py", line 36, in auth
    github_user = unicode(subprocess.check_output(shlex.split('git config --get github.user')).strip(), 'utf-8')
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'config', '--get', 'github.user']' returned non-zero exit status 1
```

**Comment by schwa** [comment]
Fixed on develop. I don't want to push new version with just this change quite yet - so if you need to use it use:

`pip install -U git+https://github.com/schwa/punic.git@develop`

Thanks
