### ISSUE TITLE
Crash calling `punic update`

### ISSUE THREAD

**Issue by brentleyjones** [schwa/punic#21]
### Cartfile

```
github "brentleyjones/xcconfigs-nbj" "v0.5"
git "git@git.companygitlab.net:dev/mobile-testing.git" "master"
```
### Cartfile.resolved

```
git "git@git.companygitlab.net:dev/mobile-testing.git" "f49195dca12081aa848342726242104ff96c676d"
github "brentleyjones/xcconfigs-nbj" "v0.5"
```
### Background

Everything is working with Carthage. This is the first command I've called with punic. I'm assuming its because I'm using an internal git repository for one of my dependencies, or that it's using the SSH syntax.
### Stacktrace

``` console
› punic update
Update
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/punic/punic_cli.py", line 369, in main
    punic_cli()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/punic/punic_cli.py", line 170, in update
    punic.resolve()
  File "/usr/local/lib/python3.5/site-packages/punic/__init__.py", line 48, in resolve
    build_order = resolver.resolve_build_order()
  File "/usr/local/lib/python3.5/site-packages/punic/resolver.py", line 112, in resolve_build_order
    graph = self.resolve()
  File "/usr/local/lib/python3.5/site-packages/punic/resolver.py", line 40, in resolve
    for dependency, revisions in self._dependencies_for_node(self.root):
  File "/usr/local/lib/python3.5/site-packages/punic/resolver.py", line 141, in _dependencies_for_node
    return self.dependencies_for_node(node)
  File "/usr/local/lib/python3.5/site-packages/punic/__init__.py", line 42, in _dependencies_for_node
    dependencies = self.dependencies_for_project_and_tag(identifier=node.identifier, tag=node.version)
  File "/usr/local/lib/python3.5/site-packages/punic/__init__.py", line 167, in dependencies_for_project_and_tag
    return [make(specification) for specification in specifications]
  File "/usr/local/lib/python3.5/site-packages/punic/__init__.py", line 167, in <listcomp>
    return [make(specification) for specification in specifications]
  File "/usr/local/lib/python3.5/site-packages/punic/__init__.py", line 160, in make
    tags = repository.revisions_for_predicate(specification.predicate)
  File "/usr/local/lib/python3.5/site-packages/punic/repository.py", line 171, in revisions_for_predicate
    return [tag for tag in self.tags if predicate.test(tag.semantic_version)]
  File "/usr/local/lib/python3.5/site-packages/memoize.py", line 11, in _property
    setattr(self, attribute, fn(self))
  File "/usr/local/lib/python3.5/site-packages/punic/repository.py", line 69, in tags
    tags = [tag for tag in output.split('\n') if tag]
TypeError: a bytes-like object is required, not 'str'
```

**Comment by schwa** [comment]
What version of python are you using btw?

**Comment by brentleyjones** [comment]
Python 3.5.2

**Comment by schwa** [comment]
Please test with `pip install -U git+https://github.com/schwa/punic.git`
