### ISSUE TITLE
Punic build command fails on Bolts framework.

### ISSUE THREAD

**Issue by calebd** [schwa/punic#25]
A `Cartfile` with only `github "facebook/facebook-ios-sdk" ~> 4.16.1` fails to build attempting to run `/usr/bin/xcrun dsymutil`.

Here is the full command output:

```
Desktop -> punic build
Build
Using xcode version: /Applications/Xcode-8.1.0.app (8.1)
Fetching: BoltsFramework/Bolts-ObjC
Fetching: facebook/facebook-ios-sdk
Building: Bolts.xcodeproj (scheme: Bolts-iOS, sdk: iphoneos, configuration: None)...
Building: Bolts.xcodeproj (scheme: Bolts-iOS, sdk: iphonesimulator, configuration: None)...
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic==0.2.3', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 369, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 147, in build
    punic.build(dependencies=deps)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 118, in build
    self._build_one(platform, project, scheme.name, configuration)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 195, in _build_one
    self._post_process(platform, products)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 252, in _post_process
    runner.check_run(command)
  File "/usr/local/lib/python2.7/site-packages/punic/runner.py", line 70, in check_run
    result = self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/runner.py", line 123, in run
    raise CalledProcessError(return_code, command, stdout)
subprocess.CalledProcessError: Command '['/usr/bin/xcrun', 'dsymutil', '/Users/calebdavenport/Desktop/Carthage/Build/iOS/Bolts.framework/Bolts', '-o', '/Users/calebdavenport/Desktop/Carthage/Build/iOS/Bolts.dSYM']' returned non-zero exit status 1
```

Running the command by hand after the framework is built results in this error:

```
Desktop -> /usr/bin/xcrun dsymutil /Users/calebdavenport/Desktop/Carthage/Build/iOS/Bolts.framework/Bolts -o /Users/calebdavenport/Desktop/Carthage/Build/iOS/Bolts.dSYM
error: cannot parse the debug map for "/Users/calebdavenport/Desktop/Carthage/Build/iOS/Bolts.framework/Bolts": The file was not recognized as a valid object file
```

The framework exists and `carthage bootstrap --platform ios --no-use-binaries` works so I'm not sure what is going on.

**Comment by calebd** [comment]
It looks like the punic-built binary:

```
asdf1 -> file /private/tmp/asdf1/Carthage/Build/iOS/Bolts.framework/Bolts 
/private/tmp/asdf1/Carthage/Build/iOS/Bolts.framework/Bolts: Mach-O universal binary with 4 architectures: [arm_v7: current ar archive] [i386: current ar archive] [x86_64] [arm64]
/private/tmp/asdf1/Carthage/Build/iOS/Bolts.framework/Bolts (for architecture armv7):	current ar archive
/private/tmp/asdf1/Carthage/Build/iOS/Bolts.framework/Bolts (for architecture i386):	current ar archive
/private/tmp/asdf1/Carthage/Build/iOS/Bolts.framework/Bolts (for architecture x86_64):	current ar archive
/private/tmp/asdf1/Carthage/Build/iOS/Bolts.framework/Bolts (for architecture arm64):	current ar archive
```

is a little bit different than the carthage-built binary:

```
asdf1 -> file /private/tmp/asdf1/Carthage-Working/Build/iOS/Bolts.framework/Bolts 
/private/tmp/asdf1/Carthage-Working/Build/iOS/Bolts.framework/Bolts: Mach-O universal binary with 4 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64: Mach-O 64-bit dynamically linked shared library x86_64] [arm_v7: Mach-O dynamically linked shared library arm_v7] [arm64: Mach-O 64-bit dynamically linked shared library arm64]
/private/tmp/asdf1/Carthage-Working/Build/iOS/Bolts.framework/Bolts (for architecture i386):	Mach-O dynamically linked shared library i386
/private/tmp/asdf1/Carthage-Working/Build/iOS/Bolts.framework/Bolts (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/private/tmp/asdf1/Carthage-Working/Build/iOS/Bolts.framework/Bolts (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
/private/tmp/asdf1/Carthage-Working/Build/iOS/Bolts.framework/Bolts (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by schwa** [comment]
It's possible punic is choosing different targets to build - will look into this.

**Comment by sebbean** [comment]
noticing same issue on my end. also with Bolts. let me know if I can be of any help

**Comment by schwa** [comment]
Yeah sorry will take a look at this ASAP.

**Comment by sebbean** [comment]
No stress papi. Obv we still have another option handy, thanks for the good
work.

**Comment by schwa** [comment]
So it looks like Carthage is building the Bolts iOS-Dynamic target and Punic is accidentally picking the Bolts iOS target (which I assume is a 'fake' static framework). I just need to make my framework finding code more sensitive.
