### ISSUE TITLE
Github enterprise repos

### ISSUE THREAD

**Issue by danielphillips** [schwa/punic#29]
Punic doesn't seem to support enterprise repositories, if I specify one I get the following Python exception.

```
daniels-mbp:iOS-Trainline danielphillips$ punic resolve
Resolve
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 369, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 120, in resolve
    punic.resolve()
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 48, in resolve
    build_order = resolver.resolve_build_order()
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 112, in resolve_build_order
    graph = self.resolve()
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 40, in resolve
    for dependency, revisions in self._dependencies_for_node(self.root):
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 141, in _dependencies_for_node
    return self.dependencies_for_node(node)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 42, in _dependencies_for_node
    dependencies = self.dependencies_for_project_and_tag(identifier=node.identifier, tag=node.version)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 161, in dependencies_for_project_and_tag
    specifications = repository.specifications_for_revision(tag)
  File "/usr/local/lib/python2.7/site-packages/punic/repository.py", line 141, in specifications_for_revision
    cartfile.read(cartfile_path)
  File "/usr/local/lib/python2.7/site-packages/punic/cartfile.py", line 44, in read
    self.specifications = [Specification.cartfile_string(line, use_ssh=self.use_ssh, overrides=self.overrides) for line in lines]
  File "/usr/local/lib/python2.7/site-packages/punic/specification.py", line 57, in cartfile_string
    identifier = ProjectIdentifier.string(match.group('address'), use_ssh=use_ssh, overrides=overrides)
  File "/usr/local/lib/python2.7/site-packages/punic/specification.py", line 107, in string
    raise Exception('No match')
Exception: No match
```

[Cartfile.resolved.txt](https://github.com/schwa/punic/files/616820/Cartfile.resolved.txt)
[Cartfile.txt](https://github.com/schwa/punic/files/616821/Cartfile.txt)

**Comment by schwa** [comment]
Your Cartfile should look like:

```
git "https://github.thetrainline.com/Bonsai/iOS-Common" ~> 3.1.3
```

(i.e. change github to git.)

Cartfile GitHub specifications look like ```github "foo/bar" ~> 3.1.3```
