### ISSUE TITLE
Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by poborin** [schwa/punic#4]
I just followed install instructions and ran a `punic update` command, however I've got a following error:

> Update
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic==0.1.11', 'console_scripts', 'punic')()
  File "/usr/local/lib/python3.5/site-packages/punic/punic_cli.py", line 354, in main
    punic_cli()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/punic/punic_cli.py", line 161, in update
    punic.resolve()
  File "/usr/local/lib/python3.5/site-packages/punic/model.py", line 50, in resolve
    build_order = resolver.resolve_build_order()
  File "/usr/local/lib/python3.5/site-packages/punic/resolver.py", line 111, in resolve_build_order
    graph = self.resolve()
  File "/usr/local/lib/python3.5/site-packages/punic/resolver.py", line 39, in resolve
    for dependency, revisions in self._dependencies_for_node(self.root):
  File "/usr/local/lib/python3.5/site-packages/punic/resolver.py", line 140, in _dependencies_for_node
    return self.dependencies_for_node(node)
  File "/usr/local/lib/python3.5/site-packages/punic/model.py", line 44, in _dependencies_for_node
    dependencies = self.dependencies_for_project_and_tag(identifier=node.identifier, tag=node.version)
  File "/usr/local/lib/python3.5/site-packages/punic/model.py", line 170, in dependencies_for_project_and_tag
    return [make(specification) for specification in specifications]
  File "/usr/local/lib/python3.5/site-packages/punic/model.py", line 170, in <listcomp>
    return [make(specification) for specification in specifications]
  File "/usr/local/lib/python3.5/site-packages/punic/model.py", line 162, in make
    repository = self._repository_for_identifier(specification.identifier)
  File "/usr/local/lib/python3.5/site-packages/punic/model.py", line 146, in _repository_for_identifier
    repository = Repository(self, identifier=identifier)
  File "/usr/local/lib/python3.5/site-packages/punic/repository.py", line 26, in __init__
    url_hash = hashlib.md5(self.identifier.remote_url).hexdigest()
TypeError: Unicode-objects must be encoded before hashing`

**Comment by reloni** [comment]
Hello.
Do you use python3? If yes, try python instead `$ brew install python`.

**Comment by schwa** [comment]
Punic should support python3 but hasn't been fully tested on it.

**Comment by poborin** [comment]
I'll try it next week, but I'm doubt that it will work. From my memory I have tried that already, but I'll give it a go anyway.

**Comment by poborin** [comment]
yes, it seems to be working with python 2.7
