### ISSUE TITLE
pydotplus requirement

### ISSUE THREAD

**Issue by mokagio** [schwa/punic#8]
Hi 👋 Thank you for the great effort you put in trying to provide a performant alternative to Carthage 💖

I just have a dev experience note on the `graph` command. I am not a Python user, and my system as little to no Python tools installed. This is what happened when running the `graph` command:

```
$ punic graph

Graph
Fetching: Alamofire/Alamofire
Fetching: SwiftyJSON/SwiftyJSON
Fetching: DaveWoodCom/XCGLogger
Fetching: Haneke/HanekeSwift
Fetching: realm/realm-cocoa
Fetching: Quick/Quick
Fetching: Quick/Nimble
Fetching: reswift/reswift
Fetching: Thomvis/BrightFutures
Fetching: featherweightlabs/FeatherweightRouter
Fetching: antitypical/Result
Writing graph file to "/Users/gio/Developer/iflix/apple-ios".
Traceback (most recent call last):
  File "/usr/local/bin/punic", line 9, in <module>
    load_entry_point('punic==0.1.15', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 365, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 219, in graph
    nx.drawing.nx_pydot.write_dot(graph, 'graph.dot')
  File "<decorator-gen-232>", line 2, in write_dot
  File "/usr/local/lib/python2.7/site-packages/networkx/utils/decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/networkx/drawing/nx_pydot.py", line 43, in write_dot
    P=to_pydot(G)
  File "/usr/local/lib/python2.7/site-packages/networkx/drawing/nx_pydot.py", line 175, in to_pydot
    import pydotplus
ImportError: No module named pydotplus
```

After installing the module using `pip`, and graphviz using Homebrew, everything worked.

Does Python provide a way to specify a tool's dependencies like you can do in the `.gemspec` of a Ruby gem? If so it would be handy to specify pydotplus there.

Thanks again for building this ☺️

**Comment by schwa** [comment]
Thanks! I wanted to make pydotplus an optional install because as you point it requires graphviz. I'll see if i can improve the experience here at the very least (maybe just trap for errors with import)
